import {
    Coins,
    Settings2,
    Brush,
    ClipboardCheck,
    Cloud,
    Leaf,
    PhoneCall,
    Heart,
    Home,
    Bath,
    UtensilsCrossed,
    WashingMachine,
    Tv,
    Bed
} from "lucide-react";

export const servicesData = [
    {
        id: "moving",
        title: "이사청소",
        homepageDesc: "\"이전 거주자의 흔적을 지우는 깔끔한 시작!\"",
        img: "/services/moving.png",
        subtitle: "살던 흔적을 지우고, 새로운 기운을 채우다!",
        desc: "전 세입자의 흔적과 생활 오염을 완벽히 제거하여\n마치 새집처럼 쾌적한 상태로 만들어 드립니다.\n전문적인 묵은때 제거로 상쾌한 출발을 도와드립니다.",
        features: [
            { icon: <Coins size={28} />, title: "정직한 견적", desc: "오염도와 평수에 따른 투명한 견적을 제시합니다." },
            { icon: <Settings2 size={28} />, title: "생활 오염 정밀 제거", desc: "주방 기름때, 욕실 물때 등 생활 흔적을 완벽히 지웁니다." },
            { icon: <Brush size={28} />, title: "고성능 장비 사용", desc: "강력한 흡입력의 청소기와 스팀기로 찌든때를 해결합니다." },
            { icon: <ClipboardCheck size={28} />, title: "꼼꼼한 마감 검수", desc: "작업 완료 후 고객님과 함께 빠진 곳 없는지 확인합니다." },
            { icon: <Cloud size={28} />, title: "고온 살균 소독", desc: "배수구, 변기 등 세균 번식 쉬운 곳을 집중 케어합니다." },
            { icon: <Leaf size={28} />, title: "냄새 제거 케어", desc: "이전 거주자의 생활취를 지우고 피톤치드로 마무리합니다." },
            { icon: <PhoneCall size={28} />, title: "당일 피드백", desc: "현장 상황을 실시간으로 안내드리고 소통합니다." },
            { icon: <Heart size={28} />, title: "책임 있는 AS", desc: "서비스 후 미진한 부분은 즉시 보완해 드립니다." },
        ],
        process: [
            { label: "예약 및 상담", img: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=200" },
            { label: "방문 전 해피콜", img: "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=200" },
            { label: "오염도 체크", img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=200" },
            { label: "정밀 클리닝", img: "https://images.unsplash.com/photo-1581578731548-c64695ce6958?auto=format&fit=crop&q=80&w=200" },
            { label: "피톤치드 마감", img: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=200" },
            { label: "고객 검수", img: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=200" },
            { label: "정산 및 완료", img: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=200" },
        ],
        scope: [
            { icon: <Home size={32} />, title: "주방/싱크대", desc: "- 기름때 제거 및 후드 세척\n- 상하부장 내부 분진 제거" },
            { icon: <Bath size={32} />, title: "욕실/수전", desc: "- 물때 및 곰팡이 제거\n- 세면대 및 변기 광택 복원" },
            { icon: <UtensilsCrossed size={32} />, title: "베란다/다용도실", desc: "- 바닥 타일 물세척\n- 배수구 오염 및 악취 제거" },
            { icon: <WashingMachine size={32} />, title: "유리창/창틀", desc: "- 창틀 먼지 흡입 및 세척\n- 유리창 얼룩 수작업 제거" },
            { icon: <Tv size={32} />, title: "거실/방", desc: "- 수납장 및 전등갓 먼지 제거\n- 바닥재 맞춤형 클리닝" },
            { icon: <Bed size={32} />, title: "마감", desc: "- 전체 공간 피톤치드 살포\n- 하수구 및 배수구 살균" },
        ]
    },
    {
        id: "residential",
        title: "거주청소",
        homepageDesc: "\"우리 가족의 건강을 지키는 프리미엄 케어!\"",
        img: "/services/residential.png",
        subtitle: "현재의 공간을 더욱 건강하게, 생활 속의 힐링!",
        desc: "짐이 있는 상태에서도 안전하고 효율적으로 청소합니다.\n가족의 건강을 위협하는 미세먼지와 세균을 정교하게 케어하여\n쾌적한 주거 환경을 유지해 드립니다.",
        features: [
            { icon: <Coins size={28} />, title: "거주 맞춤 비용", desc: "짐의 양과 청소 구역에 따른 합리적인 가격을 제안합니다." },
            { icon: <Settings2 size={28} />, title: "가구 및 가전 보호", desc: "청소 시 손상을 방지하기 위해 세심하게 보양하고 작업합니다." },
            { icon: <Brush size={28} />, title: "친환경 안심 세제", desc: "거주 공간이므로 인체에 무해한 고급 친환경 제품만 사용합니다." },
            { icon: <ClipboardCheck size={28} />, title: "일상 속 딥클린", desc: "평소 손이 닿지 않는 가구 뒤편, 천장 몰딩까지 케어합니다." },
            { icon: <Cloud size={28} />, title: "진드기 및 먼지 관리", desc: "강력한 흡입 장비로 집 안 미세먼지를 완벽 제거합니다." },
            { icon: <Leaf size={28} />, title: "공기 정화 서비스", desc: "공간 전체에 피톤치드와 오존 살균을 병행하여 정화합니다." },
            { icon: <PhoneCall size={28} />, title: "작업 시간 협의", desc: "생활 패턴에 방해되지 않도록 유연하게 일정을 조율합니다." },
            { icon: <Heart size={28} />, title: "행복한 주거 환경", desc: "깔끔해진 집에서 누리는 삶의 질 향상을 약속합니다." },
        ],
        process: [
            { label: "방문 상담 및 견적", img: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=200" },
            { label: "물건 정리 및 보양", img: "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=200" },
            { label: "구역별 순차 청소", img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=200" },
            { label: "오염 집중 관리", img: "https://images.unsplash.com/photo-1581578731548-c64695ce6958?auto=format&fit=crop&q=80&w=200" },
            { label: "살균 및 소독", img: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=200" },
            { label: "물건 재배치", img: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=200" },
            { label: "최종 검수", img: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=200" },
        ],
        scope: [
            { icon: <Home size={32} />, title: "생활 가구", desc: "- 가구 외부 및 틈새 먼지 제거\n- 침대 하단 및 소파 밑 청소" },
            { icon: <Bath size={32} />, title: "주방 정밀 클린", desc: "- 렌지 후드 및 가스레인지 세척\n- 싱크대 상판 및 벽면 기름때 제거" },
            { icon: <UtensilsCrossed size={32} />, title: "욕실 위생 관리", desc: "- 타일 곰팡이 및 물때 제거\n- 환풍구 필터 청소 및 소독" },
            { icon: <WashingMachine size={32} />, title: "바닥/벽면", desc: "- 바닥재별 맞춤형 습식 클리닝\n- 벽면 스위치 및 콘센트의 오염 제거" },
            { icon: <Tv size={32} />, title: "창틀/창문", desc: "- 외부 유리 제외한 내부 유리창 세척\n- 창틀 사이의 묵은 먼지 제거" },
            { icon: <Bed size={32} />, title: "상시 방역", desc: "- 해충 및 진드기 박멸 케어\n- 피톤치드 연무 소독" },
        ]
    },
    {
        id: "baby",
        title: "아기맞이청소",
        homepageDesc: "\"면역력 약한 아기를 위한 안심 살균!\"",
        img: "/services/baby.png",
        subtitle: "소중한 우리 아이를 위한 가장 깨끗한 첫 환경!",
        desc: "면역력이 약한 영유아를 위해 독성이 없는 안전한 세제만을 사용합니다.\n미세먼지, 진드기, 각종 알레르기 유발 요소를\n완벽하게 차단하는 프리미엄 살균 케어 서비스입니다.",
        features: [
            { icon: <Coins size={28} />, title: "맞춤형 정찰제", desc: "면적과 집중 케어 항목에 따른 투명한 비용입니다." },
            { icon: <Settings2 size={28} />, title: "무독성 세제 원칙", desc: "산모와 아이에게 안전한 천연 유래 성분 제품만 사용합니다." },
            { icon: <Brush size={28} />, title: "고온 스팀 전 구역", desc: "아이의 손이 닿는 모든 곳을 고온 스팀으로 99.9% 살균합니다." },
            { icon: <ClipboardCheck size={28} />, title: "미세먼지 제로", desc: "HEPA 필터 장비로 공기 중 미세먼지까지 포집합니다." },
            { icon: <Cloud size={28} />, title: "진드기 정밀 제거", desc: "매트리스, 카펫 등 진드기 서식 예상 구역을 집중 케어합니다." },
            { icon: <Leaf size={28} />, title: "최고급 피톤치드", desc: "새집증후군 완화와 정화 효과가 뛰어난 편백 액상을 살포합니다." },
            { icon: <PhoneCall size={28} />, title: "청소 전후 안내", desc: "작업 과정과 살균 결과를 상세히 보고해 드립니다." },
            { icon: <Heart size={28} />, title: "아기의 건강 우선", desc: "부모님의 마음으로 한 번 더 확인하고 두 번 더 닦습니다." },
        ],
        process: [
            { label: "전문 위생 상담", img: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=200" },
            { label: "장비 소독 후 입장", img: "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=200" },
            { label: "오염도 정밀 진단", img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=200" },
            { label: "천연 세제 클리닝", img: "https://images.unsplash.com/photo-1581578731548-c64695ce6958?auto=format&fit=crop&q=80&w=200" },
            { label: "집중 스팀 살균", img: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=200" },
            { label: "오존 살균 마무리", img: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=200" },
            { label: "최종 위생 검수", img: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=200" },
        ],
        scope: [
            { icon: <Home size={32} />, title: "아기방 집중", desc: "- 벽면 먼지 흡입 및 세척\n- 수납장 내부 무독성 살균" },
            { icon: <Bath size={32} />, title: "주방/젖병 존", desc: "- 젖병 세정 공간 고온 살균\n- 하부장 먼지 완벽 차단" },
            { icon: <UtensilsCrossed size={32} />, title: "욕실/아기욕조", desc: "- 욕실 천장부터 바닥까지 소독\n- 배수구 냄새 및 세균 차단" },
            { icon: <WashingMachine size={32} />, title: "거실/매트", desc: "- 놀이용 매트 틈새 먼지 제거\n- 전체 공기 중 부유먼지 관리" },
            { icon: <Tv size={32} />, title: "침구/매트리스", desc: "- 진드기 포집 및 강력 흡입\n- 피톤치드 건조 케어" },
            { icon: <Bed size={32} />, title: "전체 살균", desc: "- 전 구역 고온 스팀 마무리\n- 피톤치드 연무 코팅" },
        ]
    },
    {
        id: "rainbow",
        title: "무지개청소",
        homepageDesc: "\"냄새와 세균 걱정 없는 쾌적한 펫 환경!\"",
        img: "/services/rainbow.png",
        subtitle: "악취와 세균 박멸, 쾌적함을 다시 디자인하다!",
        desc: "특수 오염, 배수구 악취, 반려동물의 분비물 냄새 등을 전문적으로 해결합니다.\n눈에 보이는 깨끗함을 넘어,\n코끝으로 느껴지는 상쾌함까지 디자인하는 특수 클리닝 서비스입니다.",
        features: [
            { icon: <Coins size={28} />, title: "합리적 특수 견적", desc: "오염의 정도와 범위에 따른 정직한 비용 산정입니다." },
            { icon: <Settings2 size={28} />, title: "악취 근본 원인 해결", desc: "단순 향수 처리가 아닌 악취의 원인균을 박멸합니다." },
            { icon: <Brush size={28} />, title: "전용 약품 사용", desc: "오염 종류(단백질, 지방, 화학물 등)에 맞는 특수 약품을 활용합니다." },
            { icon: <ClipboardCheck size={28} />, title: "고농도 살균 케어", desc: "반려동물의 분비물 등이 깊게 밴 곳까지 깊숙이 세정합니다." },
            { icon: <Cloud size={28} />, title: "오존 탈취 장비", desc: "전문 오존 발생 장비로 공간 내 모든 냄새 분자를 분해합니다." },
            { icon: <Leaf size={28} />, title: "공기질 개선 보장", desc: "작업 후 뚜렷하게 달라진 공기의 질을 약속드립니다." },
            { icon: <PhoneCall size={28} />, title: "상황 공유 해피콜", desc: "작업 과정에서의 개선 사항을 즉시 안내드립니다." },
            { icon: <Heart size={28} />, title: "쾌적함의 완성", desc: "사라지지 않던 냄새 고민을 완벽하게 끝내 드립니다." },
        ],
        process: [
            { label: "고난도 오염 상담", img: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=200" },
            { label: "현장 오염 측정", img: "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=200" },
            { label: "원인 분석 및 처방", img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=200" },
            { label: "특수 약품 반응", img: "https://images.unsplash.com/photo-1581578731548-c64695ce6958?auto=format&fit=crop&q=80&w=200" },
            { label: "고압 세척 및 탈취", img: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=200" },
            { label: "오존 탈취 시공", img: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=200" },
            { label: "검수 및 마감", img: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=200" },
        ],
        scope: [
            { icon: <Home size={32} />, title: "배수구/하수구", desc: "- 트랩 분해 세척 및 고온 스팀\n- 악취 유발 미생물 박멸" },
            { icon: <Bath size={32} />, title: "반려동물 공간", desc: "- 밴 냄새와 털, 분비물 정밀 제거\n- 동물 전용 안전 소독제 사용" },
            { icon: <UtensilsCrossed size={32} />, title: "싱크대/후드", desc: "- 썩은 음식물 및 찌든 기름 제거\n- 배관 입구 살균 세정" },
            { icon: <WashingMachine size={32} />, title: "벽면/몰딩", desc: "- 배어버린 담배 냄새 등 탈취\n- 벽지 손상 없는 전문 약품 케어" },
            { icon: <Tv size={32} />, title: "바닥 깊숙한 곳", desc: "- 매트리스 아래, 가구 뒤편 오염\n- 바닥 틈새 오염 흡입 및 세정" },
            { icon: <Bed size={32} />, title: "공기 정화", desc: "- 오존 탈취 및 피톤치드 다중 살포\n- 잔여 약품 성분 제거" },
        ]
    },
    {
        id: "commercial",
        title: "상가청소",
        homepageDesc: "\"성공을 부르는 청결한 비즈니스 공간!\"",
        img: "/services/commercial.png",
        subtitle: "매출을 올리는 깨끗한 첫인상, 성공의 파트너!",
        desc: "매장, 사무실, 병원 등 비즈니스 공간의 품격을 높입니다.\n고객님이 다시 방문하고 싶은 공간,\n직원들이 업무에 집중할 수 있는 쾌적한 환경을 만들어 드립니다.",
        features: [
            { icon: <Coins size={28} />, title: "비즈니스 맞춤 견적", desc: "면적과 업종의 특성을 고려한 정직한 비용 제안입니다." },
            { icon: <Settings2 size={28} />, title: "체계적인 분업화", desc: "시간 엄수를 위해 넓은 공간도 전문 팀원들이 일사불란하게 작업합니다." },
            { icon: <Brush size={28} />, title: "특수 바닥재 케어", desc: "데코타일, 대리석 등 소재에 맞는 고급 장비와 약품을 사용합니다." },
            { icon: <ClipboardCheck size={28} />, title: "유리창/간판 집중", desc: "매장의 얼굴인 유리창과 간판을 투명하게 닦아 드립니다." },
            { icon: <Cloud size={28} />, title: "대형 공간 방역", desc: "많은 사람이 이용하는 만큼 철저한 살균 소독을 병행합니다." },
            { icon: <Leaf size={28} />, title: "영업 편의 고려", desc: "영업 종료 후 또는 주말에도 유연하게 일정을 맞춰 진행합니다." },
            { icon: <PhoneCall size={28} />, title: "상시 소통 관리", desc: "정기 관리 계약 시 지속적인 쾌적함을 책임집니다." },
            { icon: <Heart size={28} />, title: "성공의 동반자", desc: "깨끗해진 공간이 매출 상승으로 이어질 수 있도록 정성을 다합니다." },
        ],
        process: [
            { label: "방문 실측 및 상담", img: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=200" },
            { label: "공간 특성 분석", img: "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?auto=format&fit=crop&q=80&w=200" },
            { label: "작업 인원 투입", img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=200" },
            { label: "구역별 동시 진행", img: "https://images.unsplash.com/photo-1581578731548-c64695ce6958?auto=format&fit=crop&q=80&w=200" },
            { label: "바닥/유리 특수 클린", img: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=200" },
            { label: "최종 시설 점검", img: "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&q=80&w=200" },
            { label: "작업 보고서 제출", img: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=200" },
        ],
        scope: [
            { icon: <Home size={32} />, title: "홀/매장 내부", desc: "- 천장 조명 및 냉난방기 외부 청소\n- 선반 및 진열대 먼지 제거" },
            { icon: <Bath size={32} />, title: "공용/전용 욕실", desc: "- 불특정 다수가 쓰는 위생 공간 소독\n- 배수구 및 거울 정밀 관리" },
            { icon: <UtensilsCrossed size={32} />, title: "주방/창고", desc: "- 상업용 렌지 및 후드 대형 세정\n- 식자재 보관 창고 바닥 클리닝" },
            { icon: <WashingMachine size={32} />, title: "대형 유리창", desc: "- 내부 및 하단 외부 유리창 세척\n- 창틀 사이의 찌든 오염 제거" },
            { icon: <Tv size={32} />, title: "바닥 표면", desc: "- 바닥재 박리 및 세척\n- 폴리싱 또는 코팅 작업(옵션)" },
            { icon: <Bed size={32} />, title: "방역/마무리", desc: "- 세균성 바이러스 방역 시공\n- 대형 공기 순환 필터 점검" },
        ]
    }
];
